version: '3'
services:
  web:
    build: app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
